/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "../../types/global";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

export function Javascript(props:any) {
  const { nodes, materials } = useGLTF("models/js.glb") as GLTFResult;
  const groupRef = useRef<any>();
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.03;
      groupRef.current.rotation.x += 0.01;
    }
  });
  return (
    <group
      {...props}
      dispose={null}
      position={props.position}
      scale={3}
      ref={groupRef}
    >
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back.geometry}
          material={materials.back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOGO.geometry}
          material={materials.logo}
          position={[0.534, 0.4, 0.996]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/js.glb");
