/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "../../types/global";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

export function React(props :any) {
  const { nodes, materials } = useGLTF("models/react.glb") as GLTFResult;
  const groupRef = useRef<any>();
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y -= 0.05;
      groupRef.current.rotation.z += 0.01;
      groupRef.current.rotation.x += 0.01;
    }
  });
  return (
    <group {...props} dispose={null} ref={groupRef} scale={3}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back.geometry}
          material={materials["back.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOGO.geometry}
          material={materials["logo.004"]}
          position={[-0.003, 0.648, 0.006]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/react.glb");
